# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('foto', models.ImageField(default='avatars/default.png', null=True, upload_to='avatars/')),
                ('questao', models.CharField(choices=[(1, 'Qual o ano de nascimento do seu pai?'), (2, 'Qual o nome do seu animal de estimação?'), (3, 'Onde você nasceu?'), (4, 'Como é o nome da sua mãe?')], default=1, max_length=1)),
                ('resposta', models.CharField(max_length=128)),
                ('desativado', models.BooleanField(default=True)),
                ('amigos', models.ManyToManyField(related_name='_perfil_amigos_+', to='perfis.Perfil')),
                ('bloqueados', models.ManyToManyField(related_name='_perfil_bloqueados_+', to='perfis.Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='bloqueado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recebidos', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_feitos', to='perfis.Perfil'),
        ),
    ]
