# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
